### ISSUE TITLE
Two different LD Client objects returning different Flag values

### ISSUE THREAD

**Issue by 0shi** [launchdarkly/.net-client#59]
Gidday,

We have been attempting to diagnose an issue with one of our automated integration tests, and have worked out that the issue appears to be that two different LD Client objects are returning two different values for a single Feature Flag, for periods of up to 20-30 seconds.

Our system is set up as follows:
- Microservice architecture with > 20 services, each of which may have 1-5 replicas / instances.
- Each service has a singleton LD Client object (But as each service is a separate process (And may even be on different PCs), each replica of the service has its own singleton).
- We are currently using LD 3.4, but currently have streaming disabled due to observing some issues with the client preventing the shut down of some of our microservices (Potentially an issue with our implementation - We're still investigating). In the meantime, we are using a 1s polling interval.

Our test is set up as follows:
- We set a Feature Flag value via the REST API
- We create a new LD Client object and wait until the Feature Flag value returned is correct (In case the Feature Flag propagation from the API is slow)
- We make a call to our system, performing an operation which has a known result based on the Feature Flag's current value

We've observed that a significant portion of the time, the Feature Flag check using the new LD Client we perform as part of our test returns the expected value (That is, the Feature Flag is now in a changed but known state as far as we can tell from a testing context), but the Feature Flag value returned by the long-living LD Client in our service continues to return the previous value for periods of up to 20-30 seconds before it synchs up, causing the test to fail intermittently.

Appreciate any input on our design or our testing process.

**Comment by atrakh** [comment]
Hi @0shi,

Thanks for reaching out, and for the detailed information regarding the behavior you're experiencing.

It sounds like there's a polling desync between the two existing client instances in your test environment. When streaming is disabled, the .NET SDK will enforce a minimum polling interval of [30 seconds](https://docs.launchdarkly.com/v2.0/docs/dotnet-sdk-reference#section-customizing-your-client). If a custom polling interval less than the minimum is provided via the `WithPollingInterval` client builder method, the default interval will be used. So, with polling, it's possible for multiple client instances to be desynced for up to 30 seconds.

I can see how this behavior can be a bit misleading- we'll look into adding a warning log, or throwing an error, when an invalid interval is provided in a future release.

**Re: We currently have streaming disabled due to observing some issues with the client preventing the shut down of some of our microservices**
This is interesting- while our client does maintain a [SSE](https://en.wikipedia.org/wiki/Server-sent_events) http connection when streaming is enabled, calling the `Dispose` method should close said connection, allowing your application to terminate successfully. Have you been able to observe the described behavior with `LdClient.Dispose()` being called during shutdown?

**Comment by 0shi** [comment]
Thanks for that, we must have missed that information when disabling the Streaming behaviour.

Regarding Streaming: My apologies, I had misunderstood the reason we disabled Streaming - I've spoken more with the engineer who made the change, and while we do not explicitly call Dispose currently, the issue was actually observed during the startup of a Service in an upgrade scenario (e.g. the process was brought down and a new one was created), not the shutdown.

However, he has been unable to recreate the issue in a fresh project, so I'm happy for us to investigate that further and raise it as a separate issue if it's not on our end and nothing else comes to mind.

Thanks for your help!

**Comment by atrakh** [comment]
Hi @0shi,

Thanks for the follow-up. I'm going to close this ticket for now, but please let me know if you our your team run into any more issues and we'll pick up where we left off 😄
